version: '2'
services:
    smartcpd-elasticsearch:
        image: elasticsearch:6.4.0
        # volumes:
        #     - ~/volumes/jhipster/SmartCPD/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
        command: -Enetwork.host=0.0.0.0 -Ediscovery.type=single-node
